# Basefile Configs

RTX5070_TI:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM120_RTX5070_TI/gpgpusim.config"

RTX3080_TI:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTX3080_TI/gpgpusim.config"

RTX3080:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTX3080/gpgpusim.config"

RTX3090:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTX3090/gpgpusim.config"

RTXA6000:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000/gpgpusim.config"

RTX2070_S:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM75_RTX2070_S/gpgpusim.config"

RTX2080_TI:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM75_RTX2080_TI/gpgpusim.config"

RTXA6000_InstPref_1:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_1/gpgpusim.config"

RTXA6000_InstPref_2:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_2/gpgpusim.config"

RTXA6000_InstPref_4:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_4/gpgpusim.config"

RTXA6000_InstPref_8:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_8/gpgpusim.config"

RTXA6000_InstPref_16:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_16/gpgpusim.config"

RTXA6000_InstPref_32:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_InstPref_32/gpgpusim.config"

RTXA6000_noICache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_noICache/gpgpusim.config"


RTXA6000_SC_RAW_WAW:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_unlimited_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_unlimited_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_63_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_63_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_7_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_7_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_15_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_15_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_31_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_31_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_3_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_3_consumers/gpgpusim.config"

RTXA6000_SC_RAW_WAW_WAR_1_consumers:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_SC_RAW_WAW_WAR_1_consumers/gpgpusim.config"


RTXA6000_R1_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W1_NoRCache/gpgpusim.config"

RTXA6000_R2_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R2_W1_NoRCache/gpgpusim.config"

RTXA6000_R3_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R3_W1_NoRCache/gpgpusim.config"

RTXA6000_R4_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R4_W1_NoRCache/gpgpusim.config"

RTXA6000_R5_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R5_W1_NoRCache/gpgpusim.config"

RTXA6000_R99_W1_noRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R99_W1_NoRCache/gpgpusim.config"


RTXA6000_R2_W1_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R2_W1_YesRCache/gpgpusim.config"

RTXA6000_R3_W1_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R3_W1_YesRCache/gpgpusim.config"

RTXA6000_R4_W1_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R4_W1_YesRCache/gpgpusim.config"

RTXA6000_R5_W1_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R5_W1_YesRCache/gpgpusim.config"

RTXA6000_R99_W1_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R99_W1_YesRCache/gpgpusim.config"



RTXA6000_R1_W2_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W2_YesRCache/gpgpusim.config"

RTXA6000_R1_W3_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W3_YesRCache/gpgpusim.config"

RTXA6000_R1_W4_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W4_YesRCache/gpgpusim.config"

RTXA6000_R1_W5_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W5_YesRCache/gpgpusim.config"

RTXA6000_R1_W99_YesRCache:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/SM86_RTXA6000_R1_W2_YesRCache/gpgpusim.config"




RTX3080_TI_PTR_64_coalescers_1:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_1_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_1_prt_depCountersDecodeWarpCheck_intercoal_depCountersWarpCheck:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_prt_depCountersWarpCheck_intercoal_depCountersWarpCheck/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_depCountersDecodeWarpCheck_intercoal_depCountersWarpCheck:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_depCountersWarpCheck_intercoal_depCountersWarpCheck/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_1_prt_warpidCluster16_intercoal_oldest:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_prt_warpidCluster16_intercoal_oldest/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_1_prt_warpidCluster16_intercoal_warppoolHybrid:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_prt_warpidCluster16_intercoal_warppoolHybrid/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_warpidCluster16_intercoal_oldest:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_warpidCluster16_intercoal_oldest/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_warpidCluster16_intercoal_warppoolHybrid:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_warpidCluster16_intercoal_warppoolHybrid/gpgpusim.config"


RTX3080_TI_PTR_64_coalescers_1_Ibuffer_6:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_Ibuffer_6/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_1_Ibuffer_9:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_1_Ibuffer_9/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric_Ibuffer_6:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric_Ibuffer_6/gpgpusim.config"

RTX3080_TI_PTR_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric_Ibuffer_9:
    base_file: "$GPGPUSIM_ROOT/configs/tested-cfgs/memcoal/RTX3080_TI_ptr_64_coalescers_2_prt_depCountersDecodeGeneric_intercoal_depCountersDecodeGeneric_Ibuffer_9/gpgpusim.config"

# To keep your configurations straight - we recommend specifying
# If you are using SASS or PTX in the config:
#   For example: QV100-SASS or QV100-PTX.
SASS:
    extra_params: "#SASS-Driven Accel-Sim"

PTX:
    extra_params: "#PTX-Driven GPGPU-Sim"

############################################################################

# Extra configs - these are composable.
# The names here will be appended to the basefile name with hyphens
#   For example TITANX-L1ON-PTXPLUS
MULTI_KERNEL:
    extra_params: "-gpgpu_concurrent_kernel_sm 1"

64SM:
    extra_params: "-gpgpu_n_clusters 64"

PTXPLUS:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 10"

SM_2:
    extra_params: "-gpgpu_ptx_force_max_capability 20"

L1ON:
    extra_params: "-gmem_skip_L1D 0"

L1OFF:
    extra_params: "-gmem_skip_L1D 1"

COPYK:
    extra_params: "-perf_sim_memcpy 1"

NCOPYK:
    extra_params: "-perf_sim_memcpy 0"

5B_INSN:
    extra_params: "-gpgpu_max_insn 5000000000"

2B_INSN:
    extra_params: "-gpgpu_max_insn 2000000000"

1B_INSN:
    extra_params: "-gpgpu_max_insn 1000000000"


100M_INSN:
    extra_params: "-gpgpu_max_insn 100000000"

FLUSHL1:
    extra_params: "-gpgpu_flush_l1_cache 1"

PWR_ENABLE:
    extra_params: "-power_simulation_enabled 1"

LOCALXBAR:
    extra_params: "-network_mode 2 -icnt_in_buffer_limit 512  -icnt_out_buffer_limit 512  -icnt_subnets 2"

BOOKSIM:
    extra_params: "-network_mode 1 -inter_config_file config_volta_islip.icnt"

1455MHZ:
    extra_params: "-gpgpu_clock_domains 1455.0:1455.0:1455.0:850.0"

1132MHZ:
    extra_params: "-gpgpu_clock_domains 1132.0:1132.0:1132.0:850.0"

LINEAR:
    extra_params: "-memory_partition_indexing 0"

XOR:
    extra_params: "-memory_partition_indexing 1"

RANDOM:
    extra_params: "-memory_partition_indexing 4"

PAE:
    extra_params: "-memory_partition_indexing 3"

IPOLY:
    extra_params: "-memory_partition_indexing 2"

VISUAL:
    extra_params: "-visualizer_enabled 1"

RR:
    extra_params: "-gpgpu_scheduler lrr"

GTO:
    extra_params: "-gpgpu_scheduler gto"

128B:
    extra_params: "-gpgpu_mem_addr_mapping dramid@7;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCC.BCCSSSSS"

256B:
    extra_params: "-gpgpu_mem_addr_mapping dramid@8;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCB.CCCSSSSS"

32B:
    extra_params: "-gpgpu_mem_addr_mapping dramid@5;00000000.00000000.00000000.00000000.0000RRRR.RRRRRRRR.RBBBCCCC.BCCSSSSS"

FRFCFS:
    extra_params: "-gpgpu_dram_scheduler 1"

FCFS:
    extra_params: "-gpgpu_dram_scheduler 0"

# Experimental - for SM 60 PTXplus support
PTXPLUS_SM6:
    extra_params: "-gpgpu_ptx_convert_to_ptxplus 1 -gpgpu_ptx_force_max_capability 62 -gpgpu_ptx_force_min_capability 60"

#Accelwattch configs 
Accelwattch_SASS_SIM:
    extra_params: "-power_simulation_enabled 1
    \n-power_simulation_mode 0
    \n-accelwattch_xml_file accelwattch_sass_sim.xml"

Accelwattch_SASS_HW:
    extra_params: "-power_simulation_enabled 1
    \n-power_simulation_mode 1
    \n-accelwattch_xml_file accelwattch_sass_hw.xml"

Accelwattch_SASS_HYBRID:
    extra_params: "-power_simulation_enabled 1
    \n-power_simulation_mode 2
    \n-accelwattch_xml_file accelwattch_sass_hybrid.xml
    \n-accelwattch_hybrid_perfsim_L2_RH 1
    \n-accelwattch_hybrid_perfsim_L2_RM 1
    \n-accelwattch_hybrid_perfsim_L2_WH 1
    \n-accelwattch_hybrid_perfsim_L2_WM 1
    \n-accelwattch_hybrid_perfsim_NOC 1"

Accelwattch_PTX_SIM:
    extra_params: "-power_simulation_enabled 1
    \n-power_simulation_mode 0
    \n-accelwattch_xml_file accelwattch_ptx_sim.xml"
